# Most testing has moved to GitHub Actions
# Keep around a single build for code coverage
language: c
dist: bionic

jobs:
  include:
  - compiler: clang
    os: linux

before_script:
  - autoreconf -i -f

script:
  - ./configure --enable-code-coverage
  - make
  - make check
  - make generate_corpus

after_success:
  - mv src/sas/.libs/*.gc* .
  - mv src/spss/.libs/*.gc* .
  - mv src/stata/.libs/*.gc* .
  - mv src/.libs/*.gc* .
# - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat test-suite.log
