name: ReadStat CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: sudo apt install gettext
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Generate corpus
        run: make generate_corpus
